[package]
name = "my-prelude"
version = "0.1.0"
edition = "2021"

[dependencies]
lexical-core = { version = "0.8.5", features = ["std", "write-integers"], default-features = false, optional = true }

[features]
default = ["lexical-core"]
