[package]
name = "remove-the-minimum"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
