[package]
name = "vqsort"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.14"

[build-dependencies]
cc = "1.0.81"
system-deps = "6.2.2"

[package.metadata.system-deps]
libhwy-contrib = "1"
