[package]
name = "write-number-in-expanded-form-part-2"
version = "0.1.0"
edition = "2021"

[dependencies]
prelude = { path = "../../prelude" }
heapless = "0.7.16"
lexical-core = { version = "0.8.5", default-features = false, features = ["write-floats"] }
