[package]
name = "write-number-in-expanded-form-part-2"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"
ryu = "1.0.15"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
