[package]
name = "simple-substitution-cipher-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"
hashbrown = { version = "0.14.3", features = ["nightly"] }
rustc-hash = "1.1.0"
