[package]
name = "gangs"
version = "0.1.0"
edition = "2021"

[dependencies.hashbrown]
version = "0.13.1"
default-features = false
features = ["nightly", "inline-more"]

[dependencies.rustc-hash]
version = "1.1.0"
default-features = false
