[package]
name = "gangs"
edition = "2021"

[dependencies]
hashbrown = { version = "0.14.3", features = ["nightly"] }
rustc-hash = "1.1.0"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
