[workspace]
members = [
    "digital",
    "1kyu/*",
    "2kyu/*",
    "3kyu/*",
    "4kyu/*",
    "5kyu/*",
    "6kyu/*",
    "7kyu/*",
    "8kyu/*",
    "check-katas",
    "progress-bars",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
