[workspace]
members = [
    "prelude",
    "1kyu/*",
    "2kyu/*",
    "3kyu/*",
    "4kyu/*",
    "5kyu/*",
    "6kyu/*",
    "7kyu/*",
    "8kyu/*",
    "check-katas",
]
resolver = "2"

[profile.release]
lto = true
