[package]
name = "simple-time-difference"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }
digital = { path = "../../digital" }
vqsort = { path = "../../vqsort" }
