[package]
name = "simple-time-difference"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked = { path = "../../unchecked" }
digital = { path = "../../digital" }
vqsort = { path = "../../vqsort" }
