[package]
name = "max-min-arrays"
version = "0.1.0"
edition = "2021"

[dependencies]
prelude = { path = "../../prelude" }
vqsort = { path = "../../vqsort" }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false }
rand_pcg = "0.3.1"
