[package]
name = "simple-frequency-sort"
version = "0.1.0"
edition = "2021"

[dependencies.prelude]
path = "../../prelude"

[dependencies.hashbrown]
version = "0.14.0"
default-features = false
features = ["nightly", "inline-more"]

[dependencies.rustc-hash]
version = "1.1.0"
default-features = false

[dependencies.radsort]
version = "0.1.0"

[dev-dependencies.rand]
version = "0.8.5"
default-features = false

[dev-dependencies.rand_pcg]
version = "0.3.1"
