[package]
name = "divide-and-conquer"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.9.0"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
