[package]
name = "unique-strings"
edition = "2021"

[dependencies]
num-bigint = "0.4.4"
hashbrown = { version = "0.15.0", features = ["nightly"] }
rustc-hash = "2.0.0"
char-to-lower = { path = "../../char-to-lower" }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"

[lints]
workspace = true
