[package]
name = "how-many-nines"
version = "0.1.0"
edition = "2021"

[dependencies]
digital = { path = "../../digital" }
heapless = "0.8.0"
num-bigint = { version = "0.4.3", default-features = false }
