[package]
name = "unknown-amount-of-duplicates-one-missing-number"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
