[package]
name = "digital"
edition = "2021"

[dependencies]
heapless = { version = "0.8.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"
num-traits = "0.2.19"

[features]
default = ["heapless"]

[lints]
workspace = true

[[bench]]
name = "bench"
harness = false
