[package]
name = "barista-problem"
version = "0.1.0"
edition = "2021"

[dependencies.radsort]
version = "0.1.0"

[dev-dependencies.rand]
version = "0.8.5"
default-features = false

[dev-dependencies.rand_pcg]
version = "0.3.1"
