[package]
name = "substituting-variables-into-strings-padded-numbers"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }
digital = { path = "../../digital" }
