[package]
name = "exclamation-marks-series-number-7-remove-words-from-the-sentence-if-it-contains-one-exclamation-mark"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"

[lints]
workspace = true
