[package]
name = "flatten-and-sort-an-array"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"
vqsort = { path = "../../vqsort" }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
