[package]
name = "find-the-integer-partition-of-k-length-with-maximum-or-minimum-value-for-its-product-value"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }
