[package]
name = "search-the-0-sums-combinations-in-an-array"
edition = "2021"

[dependencies]
either = "1.9.0"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"

[lints]
workspace = true
