[package]
name = "csv-representation-of-array"
edition = "2021"

[dependencies]
unchecked-std = "1.0.0"
digital = { path = "../../digital" }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"

[lints]
workspace = true
