[package]
name = "frequency-sequence"
edition = "2021"

[dependencies]
unchecked-std = "0.1.0"
digital = { path = "../../digital" }
hashbrown = { version = "0.14.3", features = ["nightly"] }
rustc-hash = "1.1.0"
