[package]
name = "frequency-sequence"
edition = "2021"

[dependencies]
unchecked-std = "1.0.0"
digital = { path = "../../digital" }
hashbrown = { version = "0.14.3", features = ["nightly"] }
rustc-hash = "2.0.0"

[lints]
workspace = true
