[package]
name = "projectile-motion"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked = { path = "../../unchecked" }
digital = { path = "../../digital" }
libm = { version = "0.2.5", features = ["unstable"] }
