[package]
name = "delta-generators"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.16"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false }
rand_pcg = "0.3.1"
