[package]
name = "delta-generators"
version = "0.1.0"
edition = "2021"

[dependencies.heapless]
version = "0.7.16"

[dev-dependencies.rand]
version = "0.8.5"
default-features = false

[dev-dependencies.rand_pcg]
version = "0.3.1"
