[package]
name = "rusted-katana-progress-bars"
version = "0.1.0"
edition = "2021"

[dependencies]
digital = { path = "../digital" }
image = "0.25.1"
imageproc = "0.24.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
ab_glyph = "0.2.26"
heapless = "0.8.0"
