[package]
name = "find-the-difference-in-age-between-oldest-and-youngest-family-members"
edition = "2021"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"

[lints]
workspace = true
