[package]
name = "the-poet-and-the-pendulum"
version = "0.1.0"
edition = "2021"

[dependencies.prelude]
path = "../../prelude"

[dependencies.radsort]
version = "0.1.0"
default-features = false

[dev-dependencies.rand]
version = "0.8.5"

[dev-dependencies.rand_pcg]
version = "0.3.1"
