[package]
name = "gravity-flip-3d-version"
edition = "2021"

[dependencies]
vqsort-rs = "0.2.0"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std"] }
rand_pcg = "0.3.1"
