[package]
name = "unique-string-characters"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked = { path = "../../unchecked" }
hashbrown = { version = "0.14.3", features = ["nightly"] }
rustc-hash = "1.1.0"
