[package]
name = "check-katas"
version = "0.1.0"
edition = "2021"

[dependencies.prelude]
path = "../prelude"

[dependencies.attohttpc]
version = "0.24.0"
default-features = false
features = ["tls"]

[dependencies.heapless]
version = "0.7.16"
