[package]
name = "check-katas"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../unchecked-core" }
tokio = { version = "1.36.0", features = ["full"] }
reqwest = "0.11.13"
