[package]
name = "check-katas"
version = "0.1.0"
edition = "2021"

[dependencies.my-prelude]
path = "../my-prelude"

[dependencies.attohttpc]
version = "0.23.1"
default-features = false
features = ["tls"]
