[package]
name = "array-leaders-array-series-number-3"
version = "0.1.0"
edition = "2021"

[dependencies.prelude]
path = "../../prelude"

[dev-dependencies.rand]
version = "0.8.5"
default-features = false

[dev-dependencies.rand_pcg]
version = "0.3.1"
