[package]
name = "custom-fizzbuzz-array"
version = "0.1.0"
edition = "2021"

[dependencies]
my-prelude = { path = "../../my-prelude" }
lexical = { version = "6.1.1", default-features = false, features = ["std", "write-integers"] }
