[package]
name = "custom-fizzbuzz-array"
version = "0.1.0"
edition = "2021"

[dependencies.prelude]
path = "../../prelude"

[dependencies.lexical]
version = "6.1.1"
default-features = false
features = ["write-integers"]
