[package]
name = "sort-by-last-char"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }
radsort = { git = "https://github.com/JakubValtar/radsort" }
