[package]
name = "multiplication-table-for-number"
version = "0.1.0"
edition = "2021"

[dependencies]
unchecked-core = { path = "../../unchecked-core" }
digital = { path = "../../digital" }
heapless = "0.8.0"
